../drivers/exe/BST ../work_files/workload_A_1000.json BST_workload_A_1000_results.json
../drivers/exe/BST ../work_files/workload_A_5000.json BST_workload_A_5000_results.json
../drivers/exe/BST ../work_files/workload_A_10000.json BST_workload_A_10000_results.json
../drivers/exe/BST ../work_files/workload_A_20000.json BST_workload_A_20000_results.json
../drivers/exe/BST ../work_files/workload_B_1000.json BST_workload_B_1000_results.json
../drivers/exe/BST ../work_files/workload_B_5000.json BST_workload_B_5000_results.json
../drivers/exe/BST ../work_files/workload_B_10000.json BST_workload_B_10000_results.json
../drivers/exe/BST ../work_files/workload_B_20000.json BST_workload_B_20000_results.json
../drivers/exe/BST ../work_files/workload_C_1000.json BST_workload_C_1000_results.json
../drivers/exe/BST ../work_files/workload_C_5000.json BST_workload_C_5000_results.json
../drivers/exe/BST ../work_files/workload_C_10000.json BST_workload_C_10000_results.json
../drivers/exe/BST ../work_files/workload_C_20000.json BST_workload_C_20000_results.json
../drivers/exe/BST ../work_files/workload_D_1000.json BST_workload_D_1000_results.json
../drivers/exe/BST ../work_files/workload_D_5000.json BST_workload_D_5000_results.json
../drivers/exe/BST ../work_files/workload_D_10000.json BST_workload_D_10000_results.json
../drivers/exe/BST ../work_files/workload_D_20000.json BST_workload_D_20000_results.json
../drivers/exe/linkedList ../work_files/workload_A_1000.json linkedList_workload_A_1000_results.json
../drivers/exe/linkedList ../work_files/workload_A_5000.json linkedList_workload_A_5000_results.json
../drivers/exe/linkedList ../work_files/workload_A_10000.json linkedList_workload_A_10000_results.json
../drivers/exe/linkedList ../work_files/workload_A_20000.json linkedList_workload_A_20000_results.json
../drivers/exe/linkedList ../work_files/workload_B_1000.json linkedList_workload_B_1000_results.json
../drivers/exe/linkedList ../work_files/workload_B_5000.json linkedList_workload_B_5000_results.json
../drivers/exe/linkedList ../work_files/workload_B_10000.json linkedList_workload_B_10000_results.json
../drivers/exe/linkedList ../work_files/workload_B_20000.json linkedList_workload_B_20000_results.json
../drivers/exe/linkedList ../work_files/workload_C_1000.json linkedList_workload_C_1000_results.json
../drivers/exe/linkedList ../work_files/workload_C_5000.json linkedList_workload_C_5000_results.json
../drivers/exe/linkedList ../work_files/workload_C_10000.json linkedList_workload_C_10000_results.json
../drivers/exe/linkedList ../work_files/workload_C_20000.json linkedList_workload_C_20000_results.json
../drivers/exe/linkedList ../work_files/workload_D_1000.json linkedList_workload_D_1000_results.json
../drivers/exe/linkedList ../work_files/workload_D_5000.json linkedList_workload_D_5000_results.json
../drivers/exe/linkedList ../work_files/workload_D_10000.json linkedList_workload_D_10000_results.json
../drivers/exe/linkedList ../work_files/workload_D_20000.json linkedList_workload_D_20000_results.json
../drivers/exe/binaryHeap ../work_files/workload_A_1000.json binaryHeap_workload_A_1000_results.json
../drivers/exe/binaryHeap ../work_files/workload_A_5000.json binaryHeap_workload_A_5000_results.json
../drivers/exe/binaryHeap ../work_files/workload_A_10000.json binaryHeap_workload_A_10000_results.json
../drivers/exe/binaryHeap ../work_files/workload_A_20000.json binaryHeap_workload_A_20000_results.json
../drivers/exe/binaryHeap ../work_files/workload_B_1000.json binaryHeap_workload_B_1000_results.json
../drivers/exe/binaryHeap ../work_files/workload_B_5000.json binaryHeap_workload_B_5000_results.json
../drivers/exe/binaryHeap ../work_files/workload_B_10000.json binaryHeap_workload_B_10000_results.json
../drivers/exe/binaryHeap ../work_files/workload_B_20000.json binaryHeap_workload_B_20000_results.json
../drivers/exe/binaryHeap ../work_files/workload_C_1000.json binaryHeap_workload_C_1000_results.json
../drivers/exe/binaryHeap ../work_files/workload_C_5000.json binaryHeap_workload_C_5000_results.json
../drivers/exe/binaryHeap ../work_files/workload_C_10000.json binaryHeap_workload_C_10000_results.json
../drivers/exe/binaryHeap ../work_files/workload_C_20000.json binaryHeap_workload_C_20000_results.json
../drivers/exe/binaryHeap ../work_files/workload_D_1000.json binaryHeap_workload_D_1000_results.json
../drivers/exe/binaryHeap ../work_files/workload_D_5000.json binaryHeap_workload_D_5000_results.json
../drivers/exe/binaryHeap ../work_files/workload_D_10000.json binaryHeap_workload_D_10000_results.json
../drivers/exe/binaryHeap ../work_files/workload_D_20000.json binaryHeap_workload_D_20000_results.json
../drivers/exe/sortedArray ../work_files/workload_A_1000.json sortedArray_workload_A_1000_results.json
../drivers/exe/sortedArray ../work_files/workload_A_5000.json sortedArray_workload_A_5000_results.json
../drivers/exe/sortedArray ../work_files/workload_A_10000.json sortedArray_workload_A_10000_results.json
../drivers/exe/sortedArray ../work_files/workload_A_20000.json sortedArray_workload_A_20000_results.json
../drivers/exe/sortedArray ../work_files/workload_B_1000.json sortedArray_workload_B_1000_results.json
../drivers/exe/sortedArray ../work_files/workload_B_5000.json sortedArray_workload_B_5000_results.json
../drivers/exe/sortedArray ../work_files/workload_B_10000.json sortedArray_workload_B_10000_results.json
../drivers/exe/sortedArray ../work_files/workload_B_20000.json sortedArray_workload_B_20000_results.json
../drivers/exe/sortedArray ../work_files/workload_C_1000.json sortedArray_workload_C_1000_results.json
../drivers/exe/sortedArray ../work_files/workload_C_5000.json sortedArray_workload_C_5000_results.json
../drivers/exe/sortedArray ../work_files/workload_C_10000.json sortedArray_workload_C_10000_results.json
../drivers/exe/sortedArray ../work_files/workload_C_20000.json sortedArray_workload_C_20000_results.json
../drivers/exe/sortedArray ../work_files/workload_D_1000.json sortedArray_workload_D_1000_results.json
../drivers/exe/sortedArray ../work_files/workload_D_5000.json sortedArray_workload_D_5000_results.json
../drivers/exe/sortedArray ../work_files/workload_D_10000.json sortedArray_workload_D_10000_results.json
../drivers/exe/sortedArray ../work_files/workload_D_20000.json sortedArray_workload_D_20000_results.json
../drivers/exe/hashTable ../work_files/workload_A_1000.json hashTable_workload_A_1000_results.json
../drivers/exe/hashTable ../work_files/workload_A_5000.json hashTable_workload_A_5000_results.json
../drivers/exe/hashTable ../work_files/workload_A_10000.json hashTable_workload_A_10000_results.json
../drivers/exe/hashTable ../work_files/workload_A_20000.json hashTable_workload_A_20000_results.json
../drivers/exe/hashTable ../work_files/workload_B_1000.json hashTable_workload_B_1000_results.json
../drivers/exe/hashTable ../work_files/workload_B_5000.json hashTable_workload_B_5000_results.json
../drivers/exe/hashTable ../work_files/workload_B_10000.json hashTable_workload_B_10000_results.json
../drivers/exe/hashTable ../work_files/workload_B_20000.json hashTable_workload_B_20000_results.json
../drivers/exe/hashTable ../work_files/workload_C_1000.json hashTable_workload_C_1000_results.json
../drivers/exe/hashTable ../work_files/workload_C_5000.json hashTable_workload_C_5000_results.json
../drivers/exe/hashTable ../work_files/workload_C_10000.json hashTable_workload_C_10000_results.json
../drivers/exe/hashTable ../work_files/workload_C_20000.json hashTable_workload_C_20000_results.json
../drivers/exe/hashTable ../work_files/workload_D_1000.json hashTable_workload_D_1000_results.json
../drivers/exe/hashTable ../work_files/workload_D_5000.json hashTable_workload_D_5000_results.json
../drivers/exe/hashTable ../work_files/workload_D_10000.json hashTable_workload_D_10000_results.json
../drivers/exe/hashTable ../work_files/workload_D_20000.json hashTable_workload_D_20000_results.json